export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  SignIn: { role?: string } | undefined;
  SignUp: { role?: string } | undefined;
  ForgotPassword: { email?: string } | undefined;
  OTPVerification: { email: string };
  CreateNewPassword: { email: string };
  RoleSelection: undefined;
  PatientDashboard: undefined;
  DoctorDashboard: undefined;
  DoctorAppointments: undefined;
  DoctorScheduling: undefined;
  DoctorHistory: undefined;
  DoctorReports: undefined;
  DoctorProfile: undefined;
  DoctorSession: { slot: any; appointments: any[] };
  LabDashboard: undefined;
  LabAppointments: undefined;
  LabScheduling: undefined;
  LabReports: undefined;
  LabProfile: undefined;
  Reports: undefined;
  // Patient sub-screens
  BookAppointment: { doctorId?: string; doctorName?: string; specialty?: string; date?: string; time?: string; queueNumber?: number | null };
  AIHealthAssistant: undefined;
  PatientAIChat: undefined;
  FindDoctors: undefined;
  PatientAppointments: undefined;
  PatientProfile: undefined;
  DoctorAvailability: { specialty?: string };
  DoctorAvailabilityCalendar: { doctorId: string; doctorName: string; specialty: string };
  SpecialtyDoctors: { specialty: string };
  AvailabilitySelection: undefined;
  LabAvailability: undefined;
  LabBookingFlow: { lab: any; initialDate?: string; initialTime?: string; scheduleSlotId?: string };
  Settings: undefined;
  // Admin screens
  AdminDashboard: undefined;
  AdminUserManagement: undefined;
  AdminDoctorVerification: undefined;
  AdminRequests: undefined;
  AdminAnalytics: undefined;
  AdminAIMonitoring: undefined;
  AdminReports: undefined;
  AdminSettings: undefined;
  AdminLaboratories: undefined;
  AdminAppointments: undefined;
};

